version: "3"
services:

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.9-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - rabbitmqdata:/var/lib/rabbitmq
        - rabbitmqlog:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_QUEUE_NAME: hey
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin
    restart: always
  
  new_task:
    container_name: new_task
    hostname: new_task
    build:
      context: ./new_task
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        ./entrypoint.sh
    depends_on:
      - rabbitmq
  
  worker-1:
    container_name: worker-1
    hostname: worker-1
    build:
      context: ./worker
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        ./entrypoint.sh
    depends_on:
      - rabbitmq

  worker-2:
    container_name: worker-2
    hostname: worker-2
    build:
      context: ./worker
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        ./entrypoint.sh
    depends_on:
      - rabbitmq

volumes:
  rabbitmqdata:
  rabbitmqlog:
