apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: receive-logs
  name: receive-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: receive-logs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: receive-logs
    spec:
      containers:
        - args:
            - |
              ./entrypoint.sh
          command:
            - /bin/sh
            - -c
          image: receive-logs
          name: receive-logs
          resources: {}
      hostname: receive_logs
      restartPolicy: Always
status: {}
