apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rpc-server
  name: rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rpc-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: rpc-server
    spec:
      containers:
        - args:
            - |
              ./entrypoint.sh
          command:
            - /bin/sh
            - -c
          image: rpc-server
          name: rpc-server
          resources: {}
      hostname: rpc_server
      restartPolicy: Always
status: {}
