apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rpc-client
  name: rpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rpc-client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: rpc-client
    spec:
      containers:
        - args:
            - |
              ./entrypoint.sh
          command:
            - /bin/sh
            - -c
          image: rpc-client
          name: rpc-client
          resources: {}
      hostname: rpc_client
      restartPolicy: Always
status: {}
