apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: worker-2
  name: worker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker-2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: worker-2
    spec:
      containers:
        - args:
            - |
              ./entrypoint.sh
          command:
            - /bin/sh
            - -c
          image: worker-2
          name: worker-2
          resources: {}
      hostname: worker-2
      restartPolicy: Always
status: {}
